# Generated by Django 4.1.7 on 2023-04-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='cohort',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_account',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_account',
            name='university',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
