# Generated by Django 4.1.7 on 2023-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0002_user_account_cohort_user_account_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('cohort', models.CharField(blank=True, max_length=10, null=True)),
                ('university', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='university',
        ),
    ]
