# Generated by Django 4.1.7 on 2023-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0003_about_form_remove_user_account_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_form',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='about_form',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='about_form',
            name='username',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
